import { Category, Photo } from "@/lib/types/gallery";

export const CATEGORIES: Category[] = [
    "Sunset",
    "Wildlife",
    "Mangroves",
    "Guests",
    "Fishing",
    "Village",
];

export const PHOTOS: Photo[] = [
    {
        id: "1",
        src: "/images/1.jpeg",
        title: "Golden hour on the water",
        tourName: "Sunset Lagoon Cruise",
        category: "Sunset",
        tall: true,
    },
    {
        id: "2",
        src: "/images/2.jpeg",
        title: "Threading the mangrove channels",
        tourName: "Mangrove Explorer Tour",
        category: "Mangroves",
    },
    {
        id: "3",
        src: "/images/3.jpeg",
        title: "Kingfisher on the lookout",
        tourName: "Wildlife & Bird Watching Tour",
        category: "Wildlife",
        tall: true,
    },
    {
        id: "4",
        src: "/images/4.jpeg",
        title: "Guests setting off at dawn",
        tourName: "Sunrise Lagoon Tour",
        category: "Guests",
    },
    {
        id: "5",
        src: "/images/5.jpeg",
        title: "Traditional stake fishermen",
        tourName: "Fishing Village Tour",
        category: "Fishing",
        tall: true,
    },
    {
        id: "6",
        src: "/images/6.jpeg",
        title: "Cinnamon peeling demonstration",
        tourName: "Village & Culture Tour",
        category: "Village",
    },
    {
        id: "7",
        src: "/images/7.jpeg",
        title: "Silhouettes against the sky",
        tourName: "Sunset Lagoon Cruise",
        category: "Sunset",
    },
    {
        id: "8",
        src: "/images/8.jpeg",
        title: "Reflections in the narrow canal",
        tourName: "Mangrove Explorer Tour",
        category: "Mangroves",
        tall: true,
    },
    {
        id: "9",
        src: "/images/9.jpeg",
        title: "Egrets at rest",
        tourName: "Wildlife & Bird Watching Tour",
        category: "Wildlife",
    },
    {
        id: "10",
        src: "/images/10.jpeg",
        title: "Family photo on the jetty",
        tourName: "Sunrise Lagoon Tour",
        category: "Guests",
        tall: true,
    },
    {
        id: "11",
        src: "/images/11.jpeg",
        title: "Hauling in the morning catch",
        tourName: "Fishing Village Tour",
        category: "Fishing",
    },
    {
        id: "13",
        src: "/images/13.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "14",
        src: "/images/14.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "15",
        src: "/images/15.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "16",
        src: "/images/16.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "18",
        src: "/images/18.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "20",
        src: "/images/20.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "21",
        src: "/images/21.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "22",
        src: "/images/22.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "23",
        src: "/images/23.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "24",
        src: "/images/24.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "25",
        src: "/images/25.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
    {
        id: "26",
        src: "/images/26.jpeg",
        title: "Toddy tapper at work",
        tourName: "Village & Culture Tour",
        category: "Village",
        tall: true,
    },
];